const fs = require('fs');
let content = fs.readFileSync('src/components/Dashboard.tsx', 'utf8');

const patterns = [
  // Line 3143
  {
    target: `+ R\$\{" "\}\n                    \{appointmentsInPeriod\n                      .filter(\n                        (a) => (a.paymentStatus || "pending") === "pending",\n                      )\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `+ {formatMoneyUI(appointmentsInPeriod\n                      .filter(\n                        (a) => (a.paymentStatus || "pending") === "pending",\n                      )\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 3159
  {
    target: `R\$\{" "\}\n                    \{companyAppointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "paid")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `{formatMoneyUI(companyAppointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "paid")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 3167
  {
    target: `+ R\$\{" "\}\n                    \{companyAppointmentsInPeriod\n                      .filter(\n                        (a) => (a.paymentStatus || "pending") === "pending",\n                      )\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `+ {formatMoneyUI(companyAppointmentsInPeriod\n                      .filter(\n                        (a) => (a.paymentStatus || "pending") === "pending",\n                      )\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 3183
  {
    target: `R\$\{" "\}\n                    \{(() => {\n                      try {\n                        const income = JSON.parse(\n                          profileData?.generalIncomesStr || "[]",\n                        );\n                        const stringMonths = filterMonths.map(\n                          (i) =>\n                            [\n                              "Jan",\n                              "Fev",\n                              "Mar",\n                              "Abr",\n                              "Mai",\n                              "Jun",\n                              "Jul",\n                              "Ago",\n                              "Set",\n                              "Out",\n                              "Nov",\n                              "Dez",\n                            ][i],\n                        );\n                        return income\n                          .filter((c: any) =>\n                            stringMonths.includes(c.month),\n                          )\n                          .reduce(\n                            (sum: number, item: any) => sum + item.amount,\n                            0,\n                          )\n                          .toFixed(2)\n                          .replace(".", ",");\n                      } catch (err) {\n                        return "0,00";\n                      }\n                    })()\}`,
    replacement: `{(() => {\n                      try {\n                        const income = JSON.parse(\n                          profileData?.generalIncomesStr || "[]",\n                        );\n                        const stringMonths = filterMonths.map(\n                          (i) =>\n                            [\n                              "Jan",\n                              "Fev",\n                              "Mar",\n                              "Abr",\n                              "Mai",\n                              "Jun",\n                              "Jul",\n                              "Ago",\n                              "Set",\n                              "Out",\n                              "Nov",\n                              "Dez",\n                            ][i],\n                        );\n                        const val = income\n                          .filter((c: any) =>\n                            stringMonths.includes(c.month),\n                          )\n                          .reduce(\n                            (sum: number, item: any) => sum + item.amount,\n                            0,\n                          );\n                        return formatMoneyUI(val, hideFinance);\n                      } catch (err) {\n                        return formatMoneyUI(0, hideFinance);\n                      }\n                    })()}`
  },
  // Line 3230
  {
    target: `R\$\{" "\}\n                    \{(() => {\n                      try {\n                        const stringMonths = filterMonths.map(\n                          (i) =>\n                            [\n                              "Jan",\n                              "Fev",\n                              "Mar",\n                              "Abr",\n                              "Mai",\n                              "Jun",\n                              "Jul",\n                              "Ago",\n                              "Set",\n                              "Out",\n                              "Nov",\n                              "Dez",\n                            ][i],\n                        );\n                        const filteredClient = clients.filter((c: any) =>\n                          stringMonths.includes(c.month),\n                        );\n\n                        const totalClientFixedCost = filteredClient.reduce(\n                          (sum: number, c: any) => sum + (c.fixedCost || 0),\n                          0,\n                        );\n\n                        const totalClientExtraCost = filteredClient.reduce(\n                          (sum: number, c: any) => sum + (c.extraCost || 0),\n                          0,\n                        );\n\n                        const filteredCompany = companies.filter((c: any) =>\n                          stringMonths.includes(c.month),\n                        );\n\n                        const totalCompanyFixedCost = filteredCompany.reduce(\n                          (sum: number, c: any) => sum + (c.fixedCost || 0),\n                          0,\n                        );\n\n                        const totalCompanyExtraCost = filteredCompany.reduce(\n                          (sum: number, c: any) => sum + (c.extraCost || 0),\n                          0,\n                        );\n\n                        return (\n                          totalClientFixedCost +\n                          totalClientExtraCost +\n                          totalCompanyFixedCost +\n                          totalCompanyExtraCost\n                        )\n                          .toFixed(2)\n                          .replace(".", ",");\n                      } catch (err) {\n                        return "0,00";\n                      }\n                    })()\}`,
    replacement: `{(() => {\n                      try {\n                        const stringMonths = filterMonths.map(\n                          (i) =>\n                            [\n                              "Jan",\n                              "Fev",\n                              "Mar",\n                              "Abr",\n                              "Mai",\n                              "Jun",\n                              "Jul",\n                              "Ago",\n                              "Set",\n                              "Out",\n                              "Nov",\n                              "Dez",\n                            ][i],\n                        );\n                        const filteredClient = clients.filter((c: any) =>\n                          stringMonths.includes(c.month),\n                        );\n\n                        const totalClientFixedCost = filteredClient.reduce(\n                          (sum: number, c: any) => sum + (c.fixedCost || 0),\n                          0,\n                        );\n\n                        const totalClientExtraCost = filteredClient.reduce(\n                          (sum: number, c: any) => sum + (c.extraCost || 0),\n                          0,\n                        );\n\n                        const filteredCompany = companies.filter((c: any) =>\n                          stringMonths.includes(c.month),\n                        );\n\n                        const totalCompanyFixedCost = filteredCompany.reduce(\n                          (sum: number, c: any) => sum + (c.fixedCost || 0),\n                          0,\n                        );\n\n                        const totalCompanyExtraCost = filteredCompany.reduce(\n                          (sum: number, c: any) => sum + (c.extraCost || 0),\n                          0,\n                        );\n\n                        const val = (\n                          totalClientFixedCost +\n                          totalClientExtraCost +\n                          totalCompanyFixedCost +\n                          totalCompanyExtraCost\n                        );\n                        return formatMoneyUI(val, hideFinance);\n                      } catch (err) {\n                        return formatMoneyUI(0, hideFinance);\n                      }\n                    })()}`
  },
  // Line 3302
  {
    target: `R\$\{" "\}\n                      \{appointmentsInPeriod.length > 0\n                        ? (\n                            (totalPaidInPeriod + totalPendingInPeriod) /\n                            appointmentsInPeriod.length\n                          )\n                            .toFixed(2)\n                            .replace(".", ",")\n                        : "0,00"\}`,
    replacement: `{formatMoneyUI(appointmentsInPeriod.length > 0 ? (totalPaidInPeriod + totalPendingInPeriod) / appointmentsInPeriod.length : 0, hideFinance)}`
  },
  // Line 5549
  {
    target: `R\$\{" "\}\n                    \{appointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "paid")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `{formatMoneyUI(appointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "paid")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 5575
  {
    target: `R\$\{" "\}\n                    \{appointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "pending")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `{formatMoneyUI(appointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "pending")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 7410
  {
    target: `R\$\{" "\}\n                                                          \{Number(\n                                                            ap.totalAmount || 0,\n                                                          )\}`,
    replacement: `{formatMoneyUI(Number(\n                                                            ap.totalAmount || 0,\n                                                          ), hideFinance)}`
  },
  // Line 7582
  {
    target: `R\$\{" "\}\n                                              \{filteredClientAppts\n                                                .filter(\n                                                  (a: any) =>\n                                                    (a.paymentStatus ||\n                                                      "pending") === "pending",\n                                                )\n                                                .reduce(\n                                                  (a: any, b: any) =>\n                                                    a +\n                                                    Number(b.totalAmount || 0),\n                                                  0,\n                                                )\}`,
    replacement: `{formatMoneyUI(filteredClientAppts\n                                                .filter(\n                                                  (a: any) =>\n                                                    (a.paymentStatus ||\n                                                      "pending") === "pending",\n                                                )\n                                                .reduce(\n                                                  (a: any, b: any) =>\n                                                    a +\n                                                    Number(b.totalAmount || 0),\n                                                  0,\n                                                ), hideFinance)}`
  },
  // Line 7609
  {
    target: `R\$\{" "\}\n                                              \{filteredClientAppts\n                                                .filter(\n                                                  (a: any) =>\n                                                    (a.paymentStatus ||\n                                                      "pending") === "paid",\n                                                )\n                                                .reduce(\n                                                  (a: any, b: any) =>\n                                                    a +\n                                                    Number(b.totalAmount || 0),\n                                                  0,\n                                                )\}`,
    replacement: `{formatMoneyUI(filteredClientAppts\n                                                .filter(\n                                                  (a: any) =>\n                                                    (a.paymentStatus ||\n                                                      "pending") === "paid",\n                                                )\n                                                .reduce(\n                                                  (a: any, b: any) =>\n                                                    a +\n                                                    Number(b.totalAmount || 0),\n                                                  0,\n                                                ), hideFinance)}`
  },
  // Line 7723
  {
    target: `R\$\{" "\}\n                    \{companyAppointmentsInPeriod\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\n                      .toFixed(2)\n                      .replace(".", ",")\}`,
    replacement: `{formatMoneyUI(companyAppointmentsInPeriod\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 7748
  {
    target: `R\$\{" "\}\n                    \{companyAppointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "paid")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `{formatMoneyUI(companyAppointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "paid")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 7774
  {
    target: `R\$\{" "\}\n                    \{companyAppointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "pending")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0)\}`,
    replacement: `{formatMoneyUI(companyAppointmentsInPeriod\n                      .filter((a) => (a.paymentStatus || "pending") === "pending")\n                      .reduce((a, b) => a + Number(b.totalAmount || 0), 0), hideFinance)}`
  },
  // Line 7877
  {
    target: `R\$\{" "\}\n                      \{(totalCompanyPaidInPeriod + totalCompanyPendingInPeriod)\n                        .toFixed(2)\n                        .replace(".", ",")\}`,
    replacement: `{formatMoneyUI(totalCompanyPaidInPeriod + totalCompanyPendingInPeriod, hideFinance)}`
  },
  // Line 9965
  {
    target: `R\$\{" "\}\n                                            \{filteredCompanyAppts\n                                              .filter(\n                                                (a: any) =>\n                                                  (a.paymentStatus ||\n                                                    "pending") === "pending",\n                                              )\n                                              .reduce(\n                                                (a: any, b: any) =>\n                                                  a +\n                                                  Number(b.totalAmount || 0),\n                                                0,\n                                              )\}`,
    replacement: `{formatMoneyUI(filteredCompanyAppts\n                                              .filter(\n                                                (a: any) =>\n                                                  (a.paymentStatus ||\n                                                    "pending") === "pending",\n                                              )\n                                              .reduce(\n                                                (a: any, b: any) =>\n                                                  a +\n                                                  Number(b.totalAmount || 0),\n                                                0,\n                                              ), hideFinance)}`
  },
  // Line 9990
  {
    target: `R\$\{" "\}\n                                            \{filteredCompanyAppts\n                                              .filter(\n                                                (a: any) =>\n                                                  (a.paymentStatus ||\n                                                    "pending") === "paid",\n                                              )\n                                              .reduce(\n                                                (a: any, b: any) =>\n                                                  a +\n                                                  Number(b.totalAmount || 0),\n                                                0,\n                                              )\}`,
    replacement: `{formatMoneyUI(filteredCompanyAppts\n                                              .filter(\n                                                (a: any) =>\n                                                  (a.paymentStatus ||\n                                                    "pending") === "paid",\n                                              )\n                                              .reduce(\n                                                (a: any, b: any) =>\n                                                  a +\n                                                  Number(b.totalAmount || 0),\n                                                0,\n                                              ), hideFinance)}`
  }
];

for (const pat of patterns) {
  content = content.replace(pat.target, pat.replacement);
}

fs.writeFileSync('src/components/Dashboard.tsx', content, 'utf8');
